modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/theomenden/TheOmenDen.NoOutbreaks/issues"
license = "MIT"

[[mods]]
modId = "nooutbreaks"
version = "${file.jarVersion}"
displayName = "No Outbreaks!"
authors = "Alu"
description = '''
A simple fabric mod to allow for configurations of boss bars
'''
logoFile = "icon.png"

[[dependencies.nooutbreaks]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nooutbreaks]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nooutbreaks]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nooutbreaks]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "nooutbreaks.mixins.json"