on:
  workflow_dispatch:
  push:
    branches: [ "1.21" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: 'MC Publish'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: RL9joWo1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          curseforge-id: 930890
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}